slogan: "The secret of happiness is to see all the marvels of the world, and never to forget the drops of oil on the spoon."

show_heart: true

show_slogan: true

menu:
  - title: 文章
    url: archives
    intro: "All the articles."
    # icon: "fa fa-archive"
  - title: 分類
    url: categories
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: タグ
    url: tags
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: コード
    url: downloads/code
    intro: "All download codes here."

links:
  - title: Java面试指南
    url: https://www.yuque.com/itwanger/gykdzg
    intro: "svao"
    # icon: "fal fa-book-open"
  - title: Lite aliyun server
    url: https://swasnext.console.aliyun.com/servers/ap-northeast-1
    intro: "阿里云轻量服务器"
    # icon: "fa fa-github"
  - title: 习字丛林
    url: https://www.edclub.com/sportal/
    intro: "休闲，提升打字熟练度和双手协调度的好去处。"
    # icon: "fa fa-github"
  - title: "My Github"
    url: https://github.com/uncleTacitus
    intro: "My Github account."
    # icon: "fa fa-github"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: sakura.jpg
duoshuo_shortname:


# Analytics (change to yours)
google_analytics:
  enable: true
  siteid: UA-70812759-1

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
